In [4]:
import torch
import numpy as np

In [61]:
list = np.array([[1,2,3,4],[4,5,6,6],[7,8,9,9]])
tensor = torch.from_numpy(list)

In [62]:
tensor

tensor([[1, 2, 3, 4],
        [4, 5, 6, 6],
        [7, 8, 9, 9]])

In [63]:
# tensor[tensor.size(0)-1,1]
tensor.size(0)
tensor.size(1)
# tensor.size(2)



4

In [64]:
x = torch.empty(3, 4,5)

In [66]:
x

tensor([[[1.7950e+24, 4.5715e-41, 1.7950e+24, 4.5715e-41, 1.5414e-43],
         [1.6115e-43, 1.5554e-43, 1.5975e-43, 1.2752e-43, 1.6255e-43],
         [1.4153e-43, 1.5414e-43, 1.6115e-43, 1.5554e-43, 1.5975e-43],
         [6.4460e-44, 1.6115e-43, 1.4714e-43, 1.7096e-43, 1.4153e-43]],

        [[5.6052e-44, 6.7262e-44, 5.7453e-44, 6.3058e-44, 6.8664e-44],
         [6.1657e-44, 6.8664e-44, 1.3032e-43, 1.4013e-44, 1.6255e-43],
         [1.4153e-43, 1.5414e-43, 1.6115e-43, 1.5554e-43, 1.5975e-43],
         [6.4460e-44, 1.6115e-43, 1.4714e-43, 1.7096e-43, 1.4153e-43]],

        [[5.6052e-44, 6.7262e-44, 5.7453e-44, 1.4013e-44, 1.6255e-43],
         [1.4153e-43, 1.5414e-43, 1.6115e-43, 1.5554e-43, 1.5975e-43],
         [6.4460e-44, 1.6115e-43, 1.4714e-43, 1.7096e-43, 1.4153e-43],
         [5.6052e-44, 6.8664e-44, 5.7453e-44, 1.4013e-44, 4.9045e-44]]])

In [68]:
tensor[1,:]

tensor([4, 5, 6, 6])